import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

import picks from './__fixtures__/picks.json'
import {
  bestDensity,
  densityName,
  languageOf,
  selectByName,
  selectFromToc,
  splitRole,
  type DeviceSpec,
  type Incompatible,
} from './select'
import { parseToc, type ApkTargeting, type Toc, type TocApk, type TocModule } from './toc'

/*
  PARITY with bundletool. picks.json holds what `bundletool extract-apks` (1.18.3) chose for
  every device spec below, generated once by __fixtures__/make-picks.mjs from three APK sets:
  the research probe app, the same with Play Asset Delivery packs, and a matrix bundle with
  texture-format and device-tier splits and two conditional modules. No expected value here is
  typed by hand.
*/

const toc = (name: string) =>
  parseToc(readFileSync(new URL(`./__fixtures__/${name}.toc.pb`, import.meta.url)))
const fileName = (path: string) => path.split('/').pop() ?? path

/** bundletool's error sentence → the code the port gives the same refusal. */
function codeOf(error: string): Incompatible['code'] {
  if (/SDK version \(\d+\) of the device is not supported/.test(error)) return 'SDK'
  if (/ABI architectures/.test(error)) return 'ABI'
  if (/texture compression formats/.test(error)) return 'TEXTURE'
  if (/Missing APKs/.test(error)) return 'MISSING'
  return 'NO_MATCH'
}

const describeSpec = (spec: DeviceSpec) =>
  JSON.stringify(spec).replace(/"supportedLocales":|"supportedAbis":|"/g, '')

describe('selectFromToc, against bundletool extract-apks', () => {
  const sets = picks.sets as Record<string, { spec: DeviceSpec; apks?: string[]; error?: string }[]>
  for (const [name, cases] of Object.entries(sets)) {
    const parsed = toc(name)
    it.each(cases.map((c) => [describeSpec(c.spec), c] as const))(`${name} · %s`, (_, c) => {
      const result = selectFromToc(parsed, c.spec)
      if (c.apks) {
        expect(result.ok).toBe(true)
        if (result.ok) expect(result.apks.map((a) => fileName(a.path)).sort()).toEqual(c.apks)
      } else {
        expect(result.ok).toBe(false)
        if (!result.ok) expect(result.incompatible.code).toBe(codeOf(c.error ?? ''))
      }
    })
  }

  it('was generated by the bundletool release the port reads', () => {
    expect(picks.bundletool).toBe('1.18.3')
    expect(toc('matrix').bundletoolVersion).toBe('1.18.3')
  })

  it('names what made a phone incompatible, as bundletool does', () => {
    const pixel9: DeviceSpec = {
      supportedAbis: ['arm64-v8a'],
      supportedLocales: ['en-US'],
      screenDensity: 420,
      sdkVersion: 37,
    }
    expect(selectFromToc(toc('probe-all'), { ...pixel9, sdkVersion: 21 })).toEqual({
      ok: false,
      incompatible: { code: 'SDK', deviceSdk: 21, minSdk: 24 },
    })
    expect(selectFromToc(toc('probe-all'), { ...pixel9, supportedAbis: ['x86'] })).toEqual({
      ok: false,
      incompatible: {
        code: 'ABI',
        deviceAbis: ['x86'],
        appAbis: ['armeabi-v7a', 'arm64-v8a', 'x86_64'],
      },
    })
    const etc1Only = {
      ...pixel9,
      glExtensions: ['GL_OES_compressed_ETC1_RGB8_texture'],
      deviceFeatures: ['reqGlEsVersion=0x20000'],
    }
    expect(selectFromToc(toc('matrix'), etc1Only)).toMatchObject({
      ok: false,
      incompatible: { code: 'TEXTURE', deviceFormats: ['etc1'] },
    })
  })

  it('says what it could not check: GPU formats, the assumed tier, the conditions it ran', () => {
    const plain: DeviceSpec = {
      supportedAbis: ['arm64-v8a'],
      supportedLocales: ['en-US'],
      screenDensity: 420,
      sdkVersion: 37,
    }
    const result = selectFromToc(toc('matrix'), plain)
    expect(result.ok && result.notes).toEqual([
      { code: 'CONDITIONAL_MODULE', module: 'cond', included: true },
      { code: 'CONDITIONAL_MODULE', module: 'gl', included: true },
      { code: 'TEXTURES_UNCHECKED' },
      { code: 'DEVICE_TIER', tier: 1 },
    ])
    // With the phone's features listed, the conditions are checked and nothing needs saying.
    const known = selectFromToc(toc('matrix'), {
      ...plain,
      sdkVersion: 29,
      glExtensions: ['GL_KHR_texture_compression_astc_ldr'],
      deviceFeatures: ['android.hardware.camera.ar', 'reqGlEsVersion=0x30002'],
    })
    expect(known.ok && known.notes.filter((n) => n.code === 'CONDITIONAL_MODULE')).toEqual([])
  })

  it('marks install-time asset pack slices, and keeps on-demand packs out', () => {
    const result = selectFromToc(toc('probe-packs'), {
      supportedAbis: ['arm64-v8a'],
      supportedLocales: ['en-US'],
      screenDensity: 420,
      sdkVersion: 37,
    })
    expect(result.ok).toBe(true)
    if (!result.ok) return
    const packs = result.apks.filter((a) => a.assetPack)
    expect(packs.map((a) => [a.path, a.module, a.delivery])).toEqual([
      ['asset-slices/itpack-master.apk', 'itpack', 'install-time'],
    ])
  })
})

/* ---------------------------------------------------------------- *
 * Rules the probe sets cannot reach, on hand-made tables of contents
 * ---------------------------------------------------------------- */

const none = { value: [], alternatives: [] }
function apk(path: string, targeting: Partial<ApkTargeting> = {}): TocApk {
  return {
    path,
    kind: 'split',
    splitId: '',
    isMasterSplit: false,
    targeting: {
      sdk: none,
      abi: none,
      density: none,
      language: none,
      textureFormat: none,
      deviceTier: none,
      countrySet: none,
      deviceGroup: none,
      multiAbi: false,
      ...targeting,
    },
  }
}
function moduleOf(name: string, apks: TocApk[], extra: Partial<TocModule> = {}): TocModule {
  return {
    name,
    delivery: 'install-time',
    onDemandDeprecated: false,
    dependencies: [],
    targeting: null,
    apks,
    ...extra,
  }
}
function tocOf(variants: Toc['variants'], extra: Partial<Toc> = {}): Toc {
  return {
    packageName: 'com.example.app',
    bundletoolVersion: '1.18.3',
    variants,
    assetPacks: [],
    localTesting: { enabled: false, path: '' },
    defaults: {},
    ...extra,
  }
}
const variantTargeting = {
  sdk: none,
  abi: none,
  density: none,
  textureFormat: none,
  multiAbi: false,
  requiresSdkRuntime: false,
}
const phone = (extra: Partial<DeviceSpec> = {}): DeviceSpec => ({
  supportedAbis: ['arm64-v8a'],
  supportedLocales: ['en-US'],
  screenDensity: 420,
  sdkVersion: 35,
  ...extra,
})
const paths = (result: ReturnType<typeof selectFromToc>) =>
  result.ok ? result.apks.map((a) => a.path) : result.incompatible

describe('selectFromToc, on rules beyond the probe sets', () => {
  it('takes the SDK Runtime variant on Android 14+, unless the spec says the runtime is off', () => {
    const t = tocOf([
      {
        number: 0,
        targeting: { ...variantTargeting, sdk: { value: [24], alternatives: [] } },
        modules: [moduleOf('base', [apk('plain.apk')])],
      },
      {
        number: 1,
        targeting: {
          ...variantTargeting,
          sdk: { value: [34], alternatives: [] },
          requiresSdkRuntime: true,
        },
        modules: [moduleOf('base', [apk('runtime.apk')])],
      },
    ])
    expect(paths(selectFromToc(t, phone({ sdkVersion: 34 })))).toEqual(['runtime.apk'])
    expect(paths(selectFromToc(t, phone({ sdkVersion: 33 })))).toEqual(['plain.apk'])
    expect(
      paths(selectFromToc(t, phone({ sdkVersion: 35, sdkRuntime: { supported: false } }))),
    ).toEqual(['plain.apk'])
  })

  it('never uses an instant-app variant', () => {
    const t = tocOf([
      {
        number: 5,
        targeting: variantTargeting,
        modules: [moduleOf('base', [{ ...apk('instant.apk'), kind: 'instant' }])],
      },
      { number: 1, targeting: variantTargeting, modules: [moduleOf('base', [apk('base.apk')])] },
    ])
    expect(paths(selectFromToc(t, phone()))).toEqual(['base.apk'])
  })

  it('lets a preview build take parts built for the unreleased SDK', () => {
    const preview = apk('preview.apk', { sdk: { value: [10000], alternatives: [] } })
    const t = tocOf([
      { number: 0, targeting: variantTargeting, modules: [moduleOf('base', [preview])] },
    ])
    expect(paths(selectFromToc(t, phone({ codename: 'Baklava' })))).toEqual(['preview.apk'])
    // A release build is refused the way bundletool refuses it: no part fits its SDK.
    expect(paths(selectFromToc(t, phone()))).toEqual({ code: 'SDK', deviceSdk: 35, minSdk: 10000 })
  })

  it('reads delivery the old way for tables written before bundletool 0.10.2', () => {
    const modules = [
      moduleOf('base', [apk('base.apk')], { delivery: 'unknown' }),
      moduleOf('later', [apk('later.apk')], { delivery: 'unknown', onDemandDeprecated: true }),
    ]
    const t = (v: string) =>
      tocOf([{ number: 0, targeting: variantTargeting, modules }], { bundletoolVersion: v })
    expect(paths(selectFromToc(t('0.9.0'), phone()))).toEqual(['base.apk'])
    // From 0.10.2 the delivery field decides, and "unknown" is not install-time.
    expect(paths(selectFromToc(t('0.10.2'), phone()))).toEqual([])
  })

  it('brings the modules an installed module depends on', () => {
    const t = tocOf([
      {
        number: 0,
        targeting: variantTargeting,
        modules: [
          moduleOf('base', [apk('base.apk')]),
          moduleOf('feature', [apk('feature.apk')], { dependencies: ['shared'] }),
          moduleOf('shared', [apk('shared.apk')], { delivery: 'on-demand' }),
          moduleOf('other', [apk('other.apk')], { delivery: 'on-demand' }),
        ],
      },
    ])
    expect(paths(selectFromToc(t, phone()))).toEqual(['base.apk', 'feature.apk', 'shared.apk'])
  })

  it('cannot judge country conditions, and says so', () => {
    const t = tocOf([
      {
        number: 0,
        targeting: variantTargeting,
        modules: [
          moduleOf('base', [apk('base.apk')]),
          moduleOf('latam', [apk('latam.apk')], {
            targeting: { sdk: none, deviceFeatures: [], userCountries: true, deviceGroups: [] },
          }),
        ],
      },
    ])
    const result = selectFromToc(t, phone())
    expect(paths(result)).toEqual(['base.apk', 'latam.apk'])
    expect(result.ok && result.notes).toEqual([
      { code: 'CONDITIONAL_MODULE', module: 'latam', included: true },
    ])
  })

  it('refuses a module split by CPU that has nothing for this one', () => {
    // The ABI split lists the phone's ABI as a sibling, so the device check passes, yet none of
    // the module's ABI splits is for it: extract-apks' "Missing APKs" case.
    const t = tocOf([
      {
        number: 0,
        targeting: variantTargeting,
        modules: [
          moduleOf('base', [
            apk('base-master.apk'),
            apk('base-armeabi_v7a.apk', {
              abi: { value: ['armeabi-v7a'], alternatives: ['arm64-v8a'] },
            }),
          ]),
        ],
      },
    ])
    expect(paths(selectFromToc(t, phone()))).toEqual({
      code: 'MISSING',
      module: 'base',
      dimensions: ['abi'],
    })
  })

  it('notes a table built for local testing', () => {
    const t = tocOf(
      [{ number: 0, targeting: variantTargeting, modules: [moduleOf('base', [apk('b.apk')])] }],
      { localTesting: { enabled: true, path: 'local_testing' } },
    )
    const result = selectFromToc(t, phone())
    expect(result.ok && result.notes).toEqual([{ code: 'LOCAL_TESTING' }])
  })
})

describe('dimension rules', () => {
  it('compares languages the way resource folders spell them', () => {
    expect(
      ['he-IL', 'iw-IL', 'id-ID', 'in', 'yi', 'pt_BR', 'sr-Latn-RS', 'EN-us'].map(languageOf),
    ).toEqual(['iw', 'iw', 'in', 'in', 'ji', 'pt', 'sr', 'en'])
  })

  it('picks densities by Android’s rule: scaling down beats scaling up two to one', () => {
    const buckets = [120, 160, 213, 240, 320, 480, 640]
    expect(bestDensity(buckets, 420)).toBe(480)
    expect(bestDensity(buckets, 400)).toBe(480)
    expect(bestDensity(buckets, 340)).toBe(320)
    expect(bestDensity(buckets, 700)).toBe(640)
    expect(bestDensity(buckets, 100)).toBe(120)
    expect(bestDensity([160, 0xfffe], 420)).toBe(0xfffe) // "anydpi" always wins
    expect(bestDensity(buckets, 0)).toBe(160) // an unknown screen counts as mdpi
    expect(densityName(480)).toBe('xxhdpi')
    expect(densityName(420)).toBe('420dpi')
  })
})

describe('splitRole and selectByName', () => {
  it('reads what a split is for from its name', () => {
    expect(
      [
        '',
        'config.arm64_v8a',
        'config.x86_64',
        'config.xxhdpi',
        'config.vi',
        'maps',
        'maps.config.en',
        'config.astc',
      ].map(splitRole),
    ).toEqual([
      { module: 'base', kind: 'base', value: '' },
      { module: 'base', kind: 'abi', value: 'arm64-v8a' },
      { module: 'base', kind: 'abi', value: 'x86_64' },
      { module: 'base', kind: 'density', value: '480' },
      { module: 'base', kind: 'language', value: 'vi' },
      { module: 'maps', kind: 'feature', value: '' },
      { module: 'maps', kind: 'language', value: 'en' },
      { module: 'base', kind: 'other', value: 'astc' },
    ])
  })

  const set = [
    '',
    'config.armeabi_v7a',
    'config.arm64_v8a',
    'config.x86_64',
    'config.xhdpi',
    'config.xxhdpi',
    'config.en',
    'config.vi',
    'config.iw',
    'maps',
    'maps.config.xxhdpi',
    'maps.config.mdpi',
    'config.astc',
  ].map((split) => ({ split, item: split }))
  const picked = (spec: DeviceSpec) => {
    const r = selectByName(set, spec)
    return r.ok ? r.picked.map((p) => p.item).sort() : r.incompatible
  }

  it('picks, per module, the phone’s first ABI, the best density and its languages', () => {
    expect(picked(phone({ supportedLocales: ['vi-VN', 'en-US'] }))).toEqual(
      [
        '',
        'config.arm64_v8a',
        'config.xxhdpi',
        'config.en',
        'config.vi',
        'maps',
        'maps.config.xxhdpi',
      ].sort(),
    )
    expect(
      picked(
        phone({
          supportedAbis: ['armeabi-v7a', 'armeabi'],
          screenDensity: 320,
          supportedLocales: ['he-IL'],
        }),
      ),
    ).toEqual(
      ['', 'config.armeabi_v7a', 'config.iw', 'config.xhdpi', 'maps', 'maps.config.xxhdpi'].sort(),
    )
  })

  it('says why each other split was left out', () => {
    const r = selectByName(set, phone())
    expect(r.ok && r.skipped.map((s) => [s.split, s.reason])).toEqual([
      ['config.armeabi_v7a', 'abi'],
      ['config.x86_64', 'abi'],
      ['config.xhdpi', 'density'],
      ['config.vi', 'language'],
      ['config.iw', 'language'],
      ['config.astc', 'other'],
      ['maps.config.mdpi', 'density'],
    ])
  })

  it('refuses a set with native code for none of the phone’s ABIs', () => {
    expect(picked(phone({ supportedAbis: ['riscv64'] }))).toEqual({
      code: 'ABI',
      deviceAbis: ['riscv64'],
      appAbis: ['armeabi-v7a', 'arm64-v8a', 'x86_64'],
    })
  })
})
