import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

import { parsePage } from './model'
import { formatDate } from './templates/format'
import { privacyHtml } from './templates/privacy'
import { termsHtml } from './templates/terms'

/*
  GOLDEN MASTER. /terms/test-app-kaka/ and /privacy/test-app-kaka/ were generated by the
  legacy console and are live; URLs like them are what app-store submissions point at. The
  ported templates must reproduce them byte for byte from the same saved answers — so a
  re-publish from the new console changes nothing a reviewer has already seen.
*/

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../../../..')
const read = (rel: string) => readFileSync(path.join(ROOT, rel), 'utf8')

const kaka = parsePage(read('data/term-privacy/pages/test-app-kaka.json'))

describe('the ported templates reproduce the deployed pages', () => {
  it('Terms of Service, byte for byte', () => {
    expect(termsHtml(kaka)).toBe(read('terms/test-app-kaka/index.html'))
  })

  it('Privacy Policy, byte for byte', () => {
    expect(privacyHtml(kaka)).toBe(read('privacy/test-app-kaka/index.html'))
  })
})

describe('what the user typed cannot break the page', () => {
  const page = {
    ...kaka,
    app_name: 'Tom & Jerry <Pro>',
    website_url: 'https://example.com/?a=1&b="2"',
    third_party_services: ['<script>alert(1)</script>'],
  }

  it('is escaped in text and in attributes', () => {
    const html = termsHtml(page)
    expect(html).toContain('<h1>Tom &amp; Jerry &lt;Pro&gt;</h1>')
    expect(html).toContain('href="https://example.com/?a=1&amp;b=&quot;2&quot;"')
    expect(html).not.toContain('<Pro>')
  })

  it('never links a website that is not http(s), so a javascript: URL cannot run here', () => {
    for (const website_url of [
      'javascript:alert(document.domain)',
      ' JavaScript:void(0)',
      'data:text/html,x',
      'example.com',
    ]) {
      const terms = termsHtml({ ...kaka, website_url })
      const privacy = privacyHtml({ ...kaka, website_url })
      expect(terms).not.toMatch(/Website:|javascript:|data:text/i)
      expect(privacy).not.toMatch(/Website:|javascript:|data:text/i)
    }
    expect(termsHtml({ ...kaka, website_url: 'https://plsoft.vn' })).toContain(
      '<p>Website: <a href="https://plsoft.vn">https://plsoft.vn</a></p>',
    )
  })

  it('prints a data kind it does not know as typed, even one named like an object built-in', () => {
    const html = privacyHtml({ ...kaka, data_collected: ['email', 'constructor', '__proto__'] })
    expect(html).toContain('<span class="pill">Email address</span>')
    expect(html).toContain('<span class="pill">constructor</span>')
    expect(html).toContain('<span class="pill">__proto__</span>')
  })

  it('cannot inject markup through a third-party service name', () => {
    const html = privacyHtml(page)
    expect(html).toContain('&lt;script&gt;alert(1)&lt;/script&gt;')
    expect(html).not.toContain('<script>')
  })

  // The templates are the last line of defence against a hand-edited page file, on this origin.
  it('prints only real dates, so a hand-edited date cannot carry markup', () => {
    const effective_date = '"><img src=x onerror=alert(document.domain)>'
    for (const html of [
      termsHtml({ ...kaka, effective_date, last_updated: '' }),
      privacyHtml({ ...kaka, effective_date, last_updated: effective_date }),
    ]) {
      expect(html).not.toContain('<img')
      expect(html).toContain('<span>Effective: </span>')
    }
  })

  it('cannot break out of the sibling link through a hand-edited slug', () => {
    const slug = 'x"><script>alert(1)</script>'
    for (const html of [termsHtml({ ...kaka, slug }), privacyHtml({ ...kaka, slug })]) {
      expect(html).not.toContain('<script>')
      expect(html).toContain('x&quot;&gt;&lt;script&gt;')
    }
  })
})

describe('formatDate', () => {
  it("prints the legacy console's format", () => {
    expect(formatDate('2026-03-19')).toBe('19-Mar-2026')
    expect(formatDate('2024-02-29')).toBe('29-Feb-2024')
  })

  it('prints nothing for what is not a real date', () => {
    for (const value of [
      '',
      '2026-02-31',
      '2026-13-01',
      '2026-3-19',
      '2026-03-19T00:00:00Z',
      '<b>',
    ]) {
      expect(formatDate(value)).toBe('')
    }
  })
})
