/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ShellProbeRouteImport } from './routes/_shell/probe'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ProfileAbout_meRouteImport } from './routes/profile/about_me'
import { Route as ProfileContactRouteImport } from './routes/profile/contact'
import { Route as ProfilePortfolioRouteImport } from './routes/profile/portfolio'
import { Route as ProfileRelaxRouteImport } from './routes/profile/relax'
import { Route as ProfileResumeRouteImport } from './routes/profile/resume'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellProbeRoute = ShellProbeRouteImport.update({
  id: '/probe',
  path: '/probe',
  getParentRoute: () => ShellRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileAbout_meRoute = ProfileAbout_meRouteImport.update({
  id: '/about_me',
  path: '/about_me',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileContactRoute = ProfileContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfilePortfolioRoute = ProfilePortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileRelaxRoute = ProfileRelaxRouteImport.update({
  id: '/relax',
  path: '/relax',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileResumeRoute = ProfileResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => ProfileRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRouteWithChildren
  '/probe': typeof ShellProbeRoute
  '/profile/about_me': typeof ProfileAbout_meRoute
  '/profile/contact': typeof ProfileContactRoute
  '/profile/portfolio': typeof ProfilePortfolioRoute
  '/profile/relax': typeof ProfileRelaxRoute
  '/profile/resume': typeof ProfileResumeRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/probe': typeof ShellProbeRoute
  '/profile/about_me': typeof ProfileAbout_meRoute
  '/profile/contact': typeof ProfileContactRoute
  '/profile/portfolio': typeof ProfilePortfolioRoute
  '/profile/relax': typeof ProfileRelaxRoute
  '/profile/resume': typeof ProfileResumeRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/_shell/probe': typeof ShellProbeRoute
  '/profile/about_me': typeof ProfileAbout_meRoute
  '/profile/contact': typeof ProfileContactRoute
  '/profile/portfolio': typeof ProfilePortfolioRoute
  '/profile/relax': typeof ProfileRelaxRoute
  '/profile/resume': typeof ProfileResumeRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/probe'
    | '/profile/about_me'
    | '/profile/contact'
    | '/profile/portfolio'
    | '/profile/relax'
    | '/profile/resume'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/probe'
    | '/profile/about_me'
    | '/profile/contact'
    | '/profile/portfolio'
    | '/profile/relax'
    | '/profile/resume'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/profile'
    | '/_shell/probe'
    | '/profile/about_me'
    | '/profile/contact'
    | '/profile/portfolio'
    | '/profile/relax'
    | '/profile/resume'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/probe': {
      id: '/_shell/probe'
      path: '/probe'
      fullPath: '/probe'
      preLoaderRoute: typeof ShellProbeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/about_me': {
      id: '/profile/about_me'
      path: '/about_me'
      fullPath: '/profile/about_me'
      preLoaderRoute: typeof ProfileAbout_meRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/contact': {
      id: '/profile/contact'
      path: '/contact'
      fullPath: '/profile/contact'
      preLoaderRoute: typeof ProfileContactRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/portfolio': {
      id: '/profile/portfolio'
      path: '/portfolio'
      fullPath: '/profile/portfolio'
      preLoaderRoute: typeof ProfilePortfolioRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/relax': {
      id: '/profile/relax'
      path: '/relax'
      fullPath: '/profile/relax'
      preLoaderRoute: typeof ProfileRelaxRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/resume': {
      id: '/profile/resume'
      path: '/resume'
      fullPath: '/profile/resume'
      preLoaderRoute: typeof ProfileResumeRouteImport
      parentRoute: typeof ProfileRoute
    }
  }
}

interface ShellRouteChildren {
  ShellProbeRoute: typeof ShellProbeRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellProbeRoute: ShellProbeRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

interface ProfileRouteChildren {
  ProfileAbout_meRoute: typeof ProfileAbout_meRoute
  ProfileContactRoute: typeof ProfileContactRoute
  ProfilePortfolioRoute: typeof ProfilePortfolioRoute
  ProfileRelaxRoute: typeof ProfileRelaxRoute
  ProfileResumeRoute: typeof ProfileResumeRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileAbout_meRoute: ProfileAbout_meRoute,
  ProfileContactRoute: ProfileContactRoute,
  ProfilePortfolioRoute: ProfilePortfolioRoute,
  ProfileRelaxRoute: ProfileRelaxRoute,
  ProfileResumeRoute: ProfileResumeRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
