/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ShellDeviceRouteImport } from './routes/_shell/device'
import { Route as ShellXconsoleRouteImport } from './routes/_shell/xconsole'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ProfileAbout_meRouteImport } from './routes/profile/about_me'
import { Route as ProfileContactRouteImport } from './routes/profile/contact'
import { Route as ProfilePortfolioRouteImport } from './routes/profile/portfolio'
import { Route as ProfileRelaxRouteImport } from './routes/profile/relax'
import { Route as ProfileResumeRouteImport } from './routes/profile/resume'
import { Route as ProfileCvRouteImport } from './routes/profile_.cv'
import { Route as ShellXconsoleIndexRouteImport } from './routes/_shell/xconsole/index'
import { Route as ShellXconsoleIptvRouteImport } from './routes/_shell/xconsole/iptv'
import { Route as ShellXconsoleTermPrivacyRouteImport } from './routes/_shell/xconsole/term-privacy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellDeviceRoute = ShellDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => ShellRoute,
} as any)
const ShellXconsoleRoute = ShellXconsoleRouteImport.update({
  id: '/xconsole',
  path: '/xconsole',
  getParentRoute: () => ShellRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileAbout_meRoute = ProfileAbout_meRouteImport.update({
  id: '/about_me',
  path: '/about_me',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileContactRoute = ProfileContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfilePortfolioRoute = ProfilePortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileRelaxRoute = ProfileRelaxRouteImport.update({
  id: '/relax',
  path: '/relax',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileResumeRoute = ProfileResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileCvRoute = ProfileCvRouteImport.update({
  id: '/profile_/cv',
  path: '/profile/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellXconsoleIndexRoute = ShellXconsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellXconsoleRoute,
} as any)
const ShellXconsoleIptvRoute = ShellXconsoleIptvRouteImport.update({
  id: '/iptv',
  path: '/iptv',
  getParentRoute: () => ShellXconsoleRoute,
} as any)
const ShellXconsoleTermPrivacyRoute =
  ShellXconsoleTermPrivacyRouteImport.update({
    id: '/term-privacy',
    path: '/term-privacy',
    getParentRoute: () => ShellXconsoleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRouteWithChildren
  '/device': typeof ShellDeviceRoute
  '/xconsole': typeof ShellXconsoleRouteWithChildren
  '/profile/about_me': typeof ProfileAbout_meRoute
  '/profile/contact': typeof ProfileContactRoute
  '/profile/portfolio': typeof ProfilePortfolioRoute
  '/profile/relax': typeof ProfileRelaxRoute
  '/profile/resume': typeof ProfileResumeRoute
  '/profile/cv': typeof ProfileCvRoute
  '/profile/': typeof ProfileIndexRoute
  '/xconsole/iptv': typeof ShellXconsoleIptvRoute
  '/xconsole/term-privacy': typeof ShellXconsoleTermPrivacyRoute
  '/xconsole/': typeof ShellXconsoleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/device': typeof ShellDeviceRoute
  '/profile/about_me': typeof ProfileAbout_meRoute
  '/profile/contact': typeof ProfileContactRoute
  '/profile/portfolio': typeof ProfilePortfolioRoute
  '/profile/relax': typeof ProfileRelaxRoute
  '/profile/resume': typeof ProfileResumeRoute
  '/profile/cv': typeof ProfileCvRoute
  '/profile': typeof ProfileIndexRoute
  '/xconsole/iptv': typeof ShellXconsoleIptvRoute
  '/xconsole/term-privacy': typeof ShellXconsoleTermPrivacyRoute
  '/xconsole': typeof ShellXconsoleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/_shell/device': typeof ShellDeviceRoute
  '/_shell/xconsole': typeof ShellXconsoleRouteWithChildren
  '/profile/about_me': typeof ProfileAbout_meRoute
  '/profile/contact': typeof ProfileContactRoute
  '/profile/portfolio': typeof ProfilePortfolioRoute
  '/profile/relax': typeof ProfileRelaxRoute
  '/profile/resume': typeof ProfileResumeRoute
  '/profile_/cv': typeof ProfileCvRoute
  '/profile/': typeof ProfileIndexRoute
  '/_shell/xconsole/iptv': typeof ShellXconsoleIptvRoute
  '/_shell/xconsole/term-privacy': typeof ShellXconsoleTermPrivacyRoute
  '/_shell/xconsole/': typeof ShellXconsoleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/device'
    | '/xconsole'
    | '/profile/about_me'
    | '/profile/contact'
    | '/profile/portfolio'
    | '/profile/relax'
    | '/profile/resume'
    | '/profile/cv'
    | '/profile/'
    | '/xconsole/iptv'
    | '/xconsole/term-privacy'
    | '/xconsole/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/device'
    | '/profile/about_me'
    | '/profile/contact'
    | '/profile/portfolio'
    | '/profile/relax'
    | '/profile/resume'
    | '/profile/cv'
    | '/profile'
    | '/xconsole/iptv'
    | '/xconsole/term-privacy'
    | '/xconsole'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/profile'
    | '/_shell/device'
    | '/_shell/xconsole'
    | '/profile/about_me'
    | '/profile/contact'
    | '/profile/portfolio'
    | '/profile/relax'
    | '/profile/resume'
    | '/profile_/cv'
    | '/profile/'
    | '/_shell/xconsole/iptv'
    | '/_shell/xconsole/term-privacy'
    | '/_shell/xconsole/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  ProfileCvRoute: typeof ProfileCvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/device': {
      id: '/_shell/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof ShellDeviceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/xconsole': {
      id: '/_shell/xconsole'
      path: '/xconsole'
      fullPath: '/xconsole'
      preLoaderRoute: typeof ShellXconsoleRouteImport
      parentRoute: typeof ShellRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/about_me': {
      id: '/profile/about_me'
      path: '/about_me'
      fullPath: '/profile/about_me'
      preLoaderRoute: typeof ProfileAbout_meRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/contact': {
      id: '/profile/contact'
      path: '/contact'
      fullPath: '/profile/contact'
      preLoaderRoute: typeof ProfileContactRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/portfolio': {
      id: '/profile/portfolio'
      path: '/portfolio'
      fullPath: '/profile/portfolio'
      preLoaderRoute: typeof ProfilePortfolioRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/relax': {
      id: '/profile/relax'
      path: '/relax'
      fullPath: '/profile/relax'
      preLoaderRoute: typeof ProfileRelaxRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/resume': {
      id: '/profile/resume'
      path: '/resume'
      fullPath: '/profile/resume'
      preLoaderRoute: typeof ProfileResumeRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile_/cv': {
      id: '/profile_/cv'
      path: '/profile/cv'
      fullPath: '/profile/cv'
      preLoaderRoute: typeof ProfileCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/xconsole/': {
      id: '/_shell/xconsole/'
      path: '/'
      fullPath: '/xconsole/'
      preLoaderRoute: typeof ShellXconsoleIndexRouteImport
      parentRoute: typeof ShellXconsoleRoute
    }
    '/_shell/xconsole/iptv': {
      id: '/_shell/xconsole/iptv'
      path: '/iptv'
      fullPath: '/xconsole/iptv'
      preLoaderRoute: typeof ShellXconsoleIptvRouteImport
      parentRoute: typeof ShellXconsoleRoute
    }
    '/_shell/xconsole/term-privacy': {
      id: '/_shell/xconsole/term-privacy'
      path: '/term-privacy'
      fullPath: '/xconsole/term-privacy'
      preLoaderRoute: typeof ShellXconsoleTermPrivacyRouteImport
      parentRoute: typeof ShellXconsoleRoute
    }
  }
}

interface ShellXconsoleRouteChildren {
  ShellXconsoleIptvRoute: typeof ShellXconsoleIptvRoute
  ShellXconsoleTermPrivacyRoute: typeof ShellXconsoleTermPrivacyRoute
  ShellXconsoleIndexRoute: typeof ShellXconsoleIndexRoute
}

const ShellXconsoleRouteChildren: ShellXconsoleRouteChildren = {
  ShellXconsoleIptvRoute: ShellXconsoleIptvRoute,
  ShellXconsoleTermPrivacyRoute: ShellXconsoleTermPrivacyRoute,
  ShellXconsoleIndexRoute: ShellXconsoleIndexRoute,
}

const ShellXconsoleRouteWithChildren = ShellXconsoleRoute._addFileChildren(
  ShellXconsoleRouteChildren,
)

interface ShellRouteChildren {
  ShellDeviceRoute: typeof ShellDeviceRoute
  ShellXconsoleRoute: typeof ShellXconsoleRouteWithChildren
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellDeviceRoute: ShellDeviceRoute,
  ShellXconsoleRoute: ShellXconsoleRouteWithChildren,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

interface ProfileRouteChildren {
  ProfileAbout_meRoute: typeof ProfileAbout_meRoute
  ProfileContactRoute: typeof ProfileContactRoute
  ProfilePortfolioRoute: typeof ProfilePortfolioRoute
  ProfileRelaxRoute: typeof ProfileRelaxRoute
  ProfileResumeRoute: typeof ProfileResumeRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileAbout_meRoute: ProfileAbout_meRoute,
  ProfileContactRoute: ProfileContactRoute,
  ProfilePortfolioRoute: ProfilePortfolioRoute,
  ProfileRelaxRoute: ProfileRelaxRoute,
  ProfileResumeRoute: ProfileResumeRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  ProfileCvRoute: ProfileCvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
